{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:53.534Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:53.535Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:53.536Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:53.543Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:53.543Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:53.796Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:53.797Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:53.798Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:53.805Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:53.806Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:54.234Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:54.234Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:54.235Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:54.245Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:54.245Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:54.975Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:54.975Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:54.977Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:54.986Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:54.987Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:56.232Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:56.236Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:56.238Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:56.246Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:56.247Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:58.363Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:58.367Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:58.367Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:58.377Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:08:58.377Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:09:01.984Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:09:01.985Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:09:01.985Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:09:01.995Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81931,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-09-02T16:09:01.996Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":81972,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-09-02T16:09:55.824Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":82591,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: listen EADDRINUSE :::58000\n    at Object._errnoException (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    at Server.setupListenHandle [as _listen2] (net.js:1351:14)\n    at listenInCluster (net.js:1392:12)\n    at Server.listen (net.js:1476:7)\n    at main (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/as1.js:9696:10)\n    at Object.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/as1.js:1802:3)\n    at Module._compile (module.js:632:14)\n    at Object.Module._extensions..js (module.js:646:10)\n    at Module.load (module.js:554:32)\n    at tryModuleLoad (module.js:497:12)\n    at Function.Module._load (module.js:489:3)\n    at Function.Module.runMain (module.js:676:10)\n    at startup (bootstrap_node.js:187:16)\n    at bootstrap_node.js:608:3","time":"2018-09-02T16:17:15.134Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":83033,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: listen EADDRINUSE :::58000\n    at Object._errnoException (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    at Server.setupListenHandle [as _listen2] (net.js:1351:14)\n    at listenInCluster (net.js:1392:12)\n    at Server.listen (net.js:1476:7)\n    at main (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/as1.js:9696:10)\n    at Object.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/as1.js:1802:3)\n    at Module._compile (module.js:632:14)\n    at Object.Module._extensions..js (module.js:646:10)\n    at Module.load (module.js:554:32)\n    at tryModuleLoad (module.js:497:12)\n    at Function.Module._load (module.js:489:3)\n    at Function.Module.runMain (module.js:676:10)\n    at startup (bootstrap_node.js:187:16)\n    at bootstrap_node.js:608:3","time":"2018-09-02T16:20:23.472Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":85822,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: listen EADDRINUSE :::58000\n    at Object._errnoException (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    at Server.setupListenHandle [as _listen2] (net.js:1351:14)\n    at listenInCluster (net.js:1392:12)\n    at Server.listen (net.js:1476:7)\n    at main (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/as1.js:9697:10)\n    at Object.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/as1.js:1803:3)\n    at Module._compile (module.js:635:30)\n    at Object.Module._extensions..js (module.js:646:10)\n    at Module.load (module.js:554:32)\n    at tryModuleLoad (module.js:497:12)\n    at Function.Module._load (module.js:489:3)\n    at Function.Module.runMain (module.js:676:10)\n    at startup (bootstrap_node.js:187:16)\n    at bootstrap_node.js:608:3","time":"2018-09-02T16:48:21.014Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":89952,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: ReferenceError: orders is not defined\n    at Query.callback (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/printing.js:1146:33)\n    at Query.handleReadyForQuery (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/query.js:89:10)\n    at Connection.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/client.js:163:19)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-09-03T00:38:25.170Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":91887,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: Cannot read property 'customerid' of undefined\n    at Query.callback (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/orders.js:27:55)\n    at Query.handleReadyForQuery (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/query.js:89:10)\n    at Connection.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/client.js:163:19)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-09-03T01:03:43.386Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":91887,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: Cannot read property 'customerid' of undefined\n    at Query.callback (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/orders.js:27:55)\n    at Query.handleReadyForQuery (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/query.js:89:10)\n    at Connection.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/client.js:163:19)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-09-03T01:04:53.339Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":91887,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: Cannot read property 'customerid' of undefined\n    at Query.callback (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/orders.js:27:55)\n    at Query.handleReadyForQuery (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/query.js:89:10)\n    at Connection.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/client.js:163:19)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-09-03T01:16:47.106Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":763,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: Cannot read property 'forEach' of undefined\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/porders.js:1256:27\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/pool.js:82:9\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:281:11\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/pool.js:56:18\n    at Connection.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/client.js:149:7)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:121:20)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-09-03T03:26:24.654Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":3848,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-09-03T03:46:13.916Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":4355,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: listen EADDRINUSE :::58000\n    at Object._errnoException (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    at Server.setupListenHandle [as _listen2] (net.js:1351:14)\n    at listenInCluster (net.js:1392:12)\n    at Server.listen (net.js:1476:7)\n    at main (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/as1.js:9698:10)\n    at Object.<anonymous> (/Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/as1.js:1803:3)\n    at Module._compile (module.js:632:14)\n    at Object.Module._extensions..js (module.js:646:10)\n    at Module.load (module.js:554:32)\n    at tryModuleLoad (module.js:497:12)\n    at Function.Module._load (module.js:489:3)\n    at Function.Module.runMain (module.js:676:10)\n    at startup (bootstrap_node.js:187:16)\n    at bootstrap_node.js:608:3","time":"2018-09-03T03:52:12.135Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":4898,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-09-03T04:04:22.381Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":4898,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-09-03T04:04:27.200Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":7599,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: workbook.Sheets is not a function\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/printing.js:958:42\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)","time":"2018-09-03T05:43:38.401Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":7599,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: workbook.Sheets is not a function\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/printing.js:958:42\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)","time":"2018-09-03T05:49:28.460Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":8512,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: worksheet.getWorksheet is not a function\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/printing.js:962:45\n    at /Users/Fafa/node_modules/exceljs/dist/es5/doc/workbook.js:123:7\n    at Array.forEach (<anonymous>)\n    at module.exports.eachSheet (/Users/Fafa/node_modules/exceljs/dist/es5/doc/workbook.js:122:21)\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/printing.js:959:24\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)","time":"2018-09-03T05:53:56.397Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":8652,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: worksheet.getWorksheet is not a function\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/printing.js:963:45\n    at /Users/Fafa/node_modules/exceljs/dist/es5/doc/workbook.js:123:7\n    at Array.forEach (<anonymous>)\n    at module.exports.eachSheet (/Users/Fafa/node_modules/exceljs/dist/es5/doc/workbook.js:122:21)\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/printing.js:960:24\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)","time":"2018-09-03T05:55:38.182Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":9792,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: workbook.getWorksheet(...).activeCell is not a function\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/printing.js:969:49\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)","time":"2018-09-03T06:11:09.683Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":12018,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: ReferenceError: workbook is not defined\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/printing.js:1168:25\n    at /Users/Fafa/node_modules/graceful-fs/graceful-fs.js:43:10\n    at FSReqWrap.oncomplete (fs.js:135:15)","time":"2018-09-03T06:44:29.719Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":16369,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-09-03T07:42:56.833Z","v":0}
{"name":"as1","hostname":"Fafas-MBP.gateway","pid":17333,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: list.push is not a function\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/printing.js:1060:22\n    at Array.forEach (<anonymous>)\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/printing.js:1015:21\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)","time":"2018-09-03T17:31:20.267Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":20532,"level":50,"neworderdetail":true,"msg":"[neworderdetail] General exception... record \"old\" has no field \"porders_id\"","time":"2018-09-04T01:08:27.435Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":20532,"level":50,"neworderdetail":true,"msg":"[neworderdetail] General exception... record \"old\" has no field \"porders_id\"","time":"2018-09-04T01:08:54.488Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":20532,"level":50,"neworderdetail":true,"msg":"[neworderdetail] General exception... record \"old\" has no field \"porders_id\"","time":"2018-09-04T01:09:23.977Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":34664,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-09-04T04:33:04.038Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":38865,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: values.forEach is not a function\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/printing.js:1154:20\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)","time":"2018-09-04T05:26:43.398Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":39025,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: ReferenceError: array is not defined\n    at /Users/Fafa/Dropbox/AdTalk/Infinity_accounting/as1/modules/printing.js:1158:23\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)","time":"2018-09-04T05:28:27.516Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":43651,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-09-04T06:28:52.496Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":61224,"level":50,"saveproductpricing":true,"msg":"[saveproductpricing] General exception... column \"datefrom\" is of type timestamp without time zone but expression is of type bigint","time":"2018-09-05T03:16:32.813Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":62792,"level":50,"saveproductpricing":true,"msg":"[saveproductpricing] General exception... column \"datefrom\" is of type timestamp without time zone but expression is of type bigint","time":"2018-09-05T03:37:51.133Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":71095,"level":50,"saveproductpricing":true,"msg":"[saveproductpricing] General exception... column \"datefrom\" is of type timestamp without time zone but expression is of type bigint","time":"2018-09-05T05:23:08.207Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":76301,"level":50,"saveproductpricing":true,"msg":"[saveproductpricing] General exception... column \"datefrom\" is of type timestamp without time zone but expression is of type bigint","time":"2018-09-05T06:32:07.556Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":76631,"level":50,"saveproductpricing":true,"msg":"[saveproductpricing] General exception... column \"datefrom\" is of type timestamp without time zone but expression is of type bigint","time":"2018-09-05T06:36:14.132Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":76978,"level":50,"saveproductpricing":true,"msg":"[saveproductpricing] General exception... column \"datefrom\" is of type timestamp without time zone but expression is of type bigint","time":"2018-09-05T06:38:22.493Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":77129,"level":50,"saveproductpricing":true,"msg":"[saveproductpricing] General exception... column \"datefrom\" is of type timestamp without time zone but expression is of type bigint","time":"2018-09-05T06:40:30.073Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":78442,"level":50,"saveproductpricing":true,"msg":"[saveproductpricing] General exception... syntax error at or near \"SELECT\"","time":"2018-09-05T06:59:25.385Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":78670,"level":50,"saveproductpricing":true,"msg":"[saveproductpricing] General exception... syntax error at or near \"(\"","time":"2018-09-05T07:01:21.175Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":94209,"level":50,"saveproductpricing":true,"msg":"[saveproductpricing] General exception... column \"YYYY-MM-DD HH24:MI:SS\" does not exist","time":"2018-09-06T03:47:56.605Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":1258,"level":50,"saveproductpricing":true,"msg":"[saveproductpricing] General exception... multiple assignments to same column \"dateto\"","time":"2018-09-06T05:18:19.963Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":6371,"level":50,"saveproductpricing":true,"msg":"[saveproductpricing] General exception... invalid value \"Inva\" for \"YYYY\"","time":"2018-09-06T06:23:21.323Z","v":0}
{"name":"as1","hostname":"Fafas-MacBook-Pro.local","pid":7358,"level":50,"saveproductpricing":true,"msg":"[saveproductpricing] General exception... invalid value \"Inva\" for \"YYYY\"","time":"2018-09-06T06:39:38.218Z","v":0}
