{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:24.734Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:24.736Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:24.736Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:24.743Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:24.744Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:24.996Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:24.999Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:25.000Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:25.012Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:25.014Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:25.432Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:25.437Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:25.439Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:25.457Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:25.458Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:26.173Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:26.177Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:26.178Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:26.199Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:26.202Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:27.430Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:27.432Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:27.433Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:27.461Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:27.463Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:29.565Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:29.566Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:29.567Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:29.592Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:29.594Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:33.184Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:33.185Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:33.186Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:33.216Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:33.219Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:39.331Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:39.332Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:39.333Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:39.368Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:39.370Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:49.779Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:49.781Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:49.782Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:49.821Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:24:49.823Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:25:07.538Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:25:07.539Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:25:07.540Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:25:07.585Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:25:07.587Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:25:37.723Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:25:37.725Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:25:37.726Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:25:37.772Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:25:37.775Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:26:29.036Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:26:29.038Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:26:29.039Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:26:29.087Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":7944,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T02:26:29.089Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":8344,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-06T02:27:04.760Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":8344,"level":50,"listproducts":true,"msg":"[listproducts] General exception... column p1.barcode does not exist","time":"2018-08-06T02:27:08.323Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":8344,"level":50,"listorders":true,"msg":"[listorders] General exception... column o1.freightprice does not exist","time":"2018-08-06T02:27:08.677Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":8344,"level":50,"listorders":true,"msg":"[listorders] General exception... column o1.freightprice does not exist","time":"2018-08-06T02:27:08.678Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":9580,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-06T03:29:23.398Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":16174,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-06T03:30:02.166Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:56.551Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:56.553Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:56.554Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:56.558Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:56.559Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:56.815Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:56.816Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:56.817Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:56.820Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:56.820Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:57.252Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:57.253Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:57.254Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:57.256Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:57.258Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:57.996Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:57.998Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:57.999Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:58.002Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:58.003Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:59.254Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:59.255Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:59.256Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:59.258Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:13:59.259Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:01.384Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:01.385Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:01.387Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:01.390Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:01.391Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:05.002Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:05.003Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:05.005Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:05.007Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:05.008Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:11.152Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:11.154Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:11.155Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:11.156Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:11.157Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:21.604Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:21.605Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:21.606Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:21.607Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:21.608Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:39.362Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:39.364Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:39.364Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:39.366Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:14:39.367Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:15:09.546Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:15:09.548Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:15:09.548Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:15:09.551Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:15:09.552Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:16:00.858Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:16:00.859Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:16:00.860Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:16:00.862Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:16:00.863Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:17:28.087Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:17:28.088Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:17:28.089Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:17:28.090Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:17:28.092Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:19:56.369Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:19:56.370Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:19:56.372Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:19:56.374Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:19:56.375Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:24:08.440Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:24:08.441Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:24:08.442Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:24:08.446Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:24:08.447Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:31:16.937Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:31:16.938Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:31:16.939Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:31:16.942Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:31:16.943Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:43:25.397Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:43:25.398Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:43:25.399Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:43:25.400Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T05:43:25.401Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T06:04:03.774Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T06:04:03.776Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T06:04:03.777Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T06:04:03.780Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T06:04:03.781Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T06:39:09.009Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T06:39:09.010Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T06:39:09.011Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T06:39:09.016Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":1146,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-06T06:39:09.017Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":66349,"level":50,"initconnectioncache":true,"msg":"Unable to acquire db connection...","time":"2018-08-06T15:31:59.510Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":66349,"level":50,"initialisecustomerconfigcache":true,"msg":"Unable to acquire db connection...","time":"2018-08-06T15:31:59.511Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":66349,"level":50,"loginuser":true,"msg":"Unable to acquire db connection...","time":"2018-08-06T15:32:12.527Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":66400,"level":50,"posgetproduct":true,"msg":"[posgetproduct] General exception... column p1.barcode2 does not exist","time":"2018-08-06T15:43:39.453Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":67605,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-06T15:49:48.272Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":67605,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-06T16:01:38.761Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":69410,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-06T16:35:35.565Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":69822,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-06T16:42:15.638Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":69822,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-06T16:46:16.696Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":69822,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-06T16:58:26.855Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":18208,"level":50,"initconnectioncache":true,"msg":"Unable to acquire db connection...","time":"2018-08-07T00:12:57.401Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":18208,"level":50,"initialisecustomerconfigcache":true,"msg":"Unable to acquire db connection...","time":"2018-08-07T00:12:57.403Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":18208,"level":50,"loginuser":true,"msg":"Unable to acquire db connection...","time":"2018-08-07T00:14:45.423Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":13268,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-07T00:15:27.737Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":13268,"level":50,"newclientnote":true,"msg":"[newclientnote] General exception... null value in column \"clients_id\" violates not-null constraint","time":"2018-08-07T00:18:24.571Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":13268,"level":50,"neworderstatus":true,"msg":"[neworderstatus] General exception... null value in column \"orders_id\" violates not-null constraint","time":"2018-08-07T00:22:18.988Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":20380,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-07T01:50:41.433Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":20380,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-07T01:56:23.386Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":20380,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-07T03:52:26.459Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":20380,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-07T04:04:28.109Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":20380,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-07T04:07:26.155Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":20380,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-07T05:16:09.432Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":20380,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-07T05:16:11.774Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":20380,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-07T05:18:19.761Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":2216,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-07T05:46:29.122Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":2216,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-07T05:50:13.691Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":2216,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-07T06:24:27.845Z","v":0}
{"name":"as1","hostname":"Whirlwind","pid":2216,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-07T06:26:49.422Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:24.537Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:24.539Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:24.539Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:24.544Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:24.545Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:24.799Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:24.801Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:24.802Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:24.807Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:24.810Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:25.238Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:25.239Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:25.240Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:25.245Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:25.247Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:25.977Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:25.978Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:25.979Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:25.986Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:25.988Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:27.237Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:27.238Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:27.239Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:27.245Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:27.246Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:29.366Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:29.367Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:29.368Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:29.378Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:29.379Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:32.985Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:32.986Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:32.987Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:32.998Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:33.000Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:39.132Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:39.133Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:185:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:39.133Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:39.147Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":24888,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED 127.0.0.1:6379\n    at RedisClient.on_error (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:189:24)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/primus-redis-rooms/node_modules/redis/index.js:95:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","time":"2018-08-08T00:50:39.148Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":25230,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T00:52:55.435Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":26149,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: Cannot read property 'length' of undefined\n    at /Users/rumpus/Webstorm/as1/modules/pos.js:146:53\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/lib/pool.js:82:9\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:281:11\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/lib/pool.js:56:18\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:149:7)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:121:20)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T00:58:54.369Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":26149,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: Cannot read property 'length' of undefined\n    at /Users/rumpus/Webstorm/as1/modules/pos.js:146:53\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/lib/pool.js:82:9\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:281:11\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/lib/pool.js:56:18\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:149:7)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:121:20)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T00:58:54.802Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":26149,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: Cannot read property 'length' of undefined\n    at /Users/rumpus/Webstorm/as1/modules/pos.js:146:53\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/lib/pool.js:82:9\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:281:11\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/lib/pool.js:56:18\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:149:7)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:121:20)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T00:59:06.427Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":26285,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T01:54:45.771Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":26285,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T03:21:25.873Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":26285,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T03:24:07.243Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":26285,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T03:25:43.361Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":26285,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T03:27:04.569Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":26285,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T03:32:15.558Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":26285,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T03:42:15.049Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":26285,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T04:07:09.676Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":85832,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:24:25.620Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":85832,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:24:26.983Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":85832,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:24:32.008Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":85832,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:24:35.081Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":85832,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:24:44.267Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":85832,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:24:44.705Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":85832,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:24:45.021Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":85832,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:24:45.217Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":85832,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:24:45.399Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":85832,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:24:45.578Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86200,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:25:14.408Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86200,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:25:16.294Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86200,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:25:16.494Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86200,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:25:16.696Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86200,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:25:16.901Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86200,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:25:17.077Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86200,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:25:17.266Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86200,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:25:17.454Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86200,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:25:17.648Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86200,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:25:17.837Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86346,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:26:33.016Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86346,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:26:34.555Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86346,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:26:34.755Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86346,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:26:34.936Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86346,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T04:27:28.864Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86346,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:27:34.234Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86346,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:27:35.762Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86346,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:27:36.624Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86776,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T04:29:55.809Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86776,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: this.callback is not a function\n    at Query.handleError (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/query.js:106:17)\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:30:40.748Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86993,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T04:31:27.401Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86993,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T04:31:29.362Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86993,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T04:31:30.732Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86993,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: Cannot read property 'substring' of null\n    at /Users/rumpus/Webstorm/as1/modules/pos.js:142:20\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/lib/pool.js:82:9\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:281:11\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/lib/pool.js:56:18\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:149:7)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:121:20)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:33:50.577Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86993,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: TypeError: Cannot read property 'substring' of null\n    at /Users/rumpus/Webstorm/as1/modules/pos.js:142:20\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/lib/pool.js:82:9\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:281:11\n    at /Users/rumpus/Webstorm/as1/node_modules/pg/lib/pool.js:56:18\n    at Connection.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/client.js:149:7)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:121:20)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/Users/rumpus/Webstorm/as1/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","time":"2018-08-08T04:33:51.251Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86993,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T04:49:22.831Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":86993,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T04:50:27.582Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":91862,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T04:51:14.436Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T04:53:46.441Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T05:14:27.577Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T05:19:56.350Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T05:20:45.131Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T05:20:45.881Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T05:20:46.865Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T05:20:47.284Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T05:41:59.698Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T05:52:51.756Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T05:54:04.655Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T06:19:53.883Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T06:43:28.564Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T06:53:32.990Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T06:56:24.198Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T06:56:24.953Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T06:56:25.756Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":92307,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-08T06:59:24.939Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":4251,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-09T01:00:50.233Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":4359,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-09T01:09:09.738Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":8077,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: ReferenceError: $ is not defined\n    at main (/Users/rumpus/Webstorm/as1/as1.js:9574:2)\n    at Object.<anonymous> (/Users/rumpus/Webstorm/as1/as1.js:1725:3)\n    at Module._compile (module.js:632:14)\n    at Object.Module._extensions..js (module.js:646:10)\n    at Module.load (module.js:554:32)\n    at tryModuleLoad (module.js:497:12)\n    at Function.Module._load (module.js:489:3)\n    at Function.Module.runMain (module.js:676:10)\n    at startup (bootstrap_node.js:187:16)\n    at bootstrap_node.js:608:3","time":"2018-08-09T01:11:35.053Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":8208,"level":50,"as1":true,"msg":"[worker] Uncaught exception, stack trace: ReferenceError: XMLHttpRequest is not defined\n    at main (/Users/rumpus/Webstorm/as1/as1.js:9574:12)\n    at Object.<anonymous> (/Users/rumpus/Webstorm/as1/as1.js:1725:3)\n    at Module._compile (module.js:632:14)\n    at Object.Module._extensions..js (module.js:646:10)\n    at Module.load (module.js:554:32)\n    at tryModuleLoad (module.js:497:12)\n    at Function.Module._load (module.js:489:3)\n    at Function.Module.runMain (module.js:676:10)\n    at startup (bootstrap_node.js:187:16)\n    at bootstrap_node.js:608:3","time":"2018-08-09T01:12:21.329Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":16730,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-09T02:04:52.493Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":47640,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-09T04:11:27.474Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":47640,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-09T04:15:49.026Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":47640,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-09T04:17:07.265Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":47640,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-09T04:20:05.390Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":47640,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-09T04:29:14.277Z","v":0}
{"name":"as1","hostname":"Mitchams-iMac.local","pid":47640,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-09T05:44:25.580Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":32356,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-09T16:29:44.735Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":32356,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-09T16:31:36.751Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":32356,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-09T16:37:47.088Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":32356,"level":50,"loginuser":true,"msg":"[login] General exception... Invalid login...","time":"2018-08-09T16:50:25.641Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":37061,"level":50,"poscashsale":true,"msg":"[poscashsale] General exception... mobileno is not defined","time":"2018-08-09T17:28:11.049Z","v":0}
{"name":"as1","hostname":"Ians-MacBook-Pro.local","pid":38394,"level":50,"poscashsale":true,"msg":"[poscashsale] General exception... __.stripnonnumeric is not a function","time":"2018-08-09T17:46:13.591Z","v":0}
